defaults:
  - _self_
  - model: ElderNet
  - augmentation: all
  - dataloader: ten_sec

model:
  num_epochs: 100
  warmup_epochs: 5
  is_mtl: False
  is_simclr: False
  is_classification: False
  is_regression: True
  uncertainty: False
  batch_norm: True
  num_layers_regressor: 2
  lr: 0.0001
  batch_size: 512
  wd: 0.1
  patience: 5
  weights_path: outputs\gait_speed\TVS_ElderNet_pretrained_True_data_10_overlap_9Sec\final_training\final_model.pt
  plot: True

data:
  labels: gait_speed.p
  data_root:  data_parsing\ten_seconds_windows_overlap_9sec_0.5nan_ratio\Test
  log_path: outputs\gait_speed\TVS_ElderNet_pretrained_True_data_10_overlap_9Sec\testing
  overlap: 9Sec
  output_size: 1
  max_mu: 2 # 2 m/s for speed, 2m for stride length, 160 steps/min for cadence, and 1 for regularity
  measure: 'gait speed'
  unit: cm/s
  title: 'Gait Speed'